sudo: required
services:
  - docker

before_install:
  - docker build -t denissweat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true denissweat/react-test npm test

after_success:
  - docker build -t denissweat/multi-client ./client
  - docker build -t denissweat/multi-nginx ./nginx
  - docker build -t denissweat/multi-server ./server
  - docker build -t denissweat/multi-worker ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push them up
  - docker push denissweat/multi-client
  - docker push denissweat/multi-nginx
  - docker push denissweat/multi-server
  - docker push denissweat/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-636809558112
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
